// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium_2.Context;

#nullable disable

namespace kolokwium_2.Migrations
{
    [DbContext(typeof(DrinksDbContext))]
    partial class DrinksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kolokwium_2.Entities.Beverage", b =>
                {
                    b.Property<int>("IdBeverage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdBeverage")
                        .HasName("Beverage_pk");

                    b.ToTable("Beverage", (string)null);

                    b.HasData(
                        new
                        {
                            IdBeverage = 1,
                            Name = "Lemoniada",
                            Price = 4.5m
                        },
                        new
                        {
                            IdBeverage = 2,
                            Name = "Wudka",
                            Price = 7.99m
                        },
                        new
                        {
                            IdBeverage = 3,
                            Name = "Sok z gumijagudek",
                            Price = 15.3m
                        });
                });

            modelBuilder.Entity("kolokwium_2.Entities.BeverageIngredient", b =>
                {
                    b.Property<int>("IdBeverage")
                        .HasColumnType("int");

                    b.Property<int>("IdIngredient")
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdBeverage", "IdIngredient")
                        .HasName("BeverageIngredient_pk");

                    b.HasIndex("IdIngredient");

                    b.ToTable("BeverageIngredient", (string)null);

                    b.HasData(
                        new
                        {
                            IdBeverage = 1,
                            IdIngredient = 1,
                            Amount = "20"
                        },
                        new
                        {
                            IdBeverage = 2,
                            IdIngredient = 2,
                            Amount = "15"
                        },
                        new
                        {
                            IdBeverage = 3,
                            IdIngredient = 3,
                            Amount = "10"
                        });
                });

            modelBuilder.Entity("kolokwium_2.Entities.Ingredient", b =>
                {
                    b.Property<int>("IdIngredient")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("NonAlcoholic")
                        .HasColumnType("bit");

                    b.HasKey("IdIngredient")
                        .HasName("Ingredient_pk");

                    b.ToTable("Ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            IdIngredient = 1,
                            Name = "Cytryna",
                            NonAlcoholic = true
                        },
                        new
                        {
                            IdIngredient = 2,
                            Name = "Nie pamietam co",
                            NonAlcoholic = false
                        },
                        new
                        {
                            IdIngredient = 3,
                            Name = "Gumijagoda",
                            NonAlcoholic = false
                        });
                });

            modelBuilder.Entity("kolokwium_2.Entities.BeverageIngredient", b =>
                {
                    b.HasOne("kolokwium_2.Entities.Beverage", "Beverage")
                        .WithMany("Ingredients")
                        .HasForeignKey("IdBeverage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BecerageIngredient_Beverage");

                    b.HasOne("kolokwium_2.Entities.Ingredient", "Ingredient")
                        .WithMany("Beverages")
                        .HasForeignKey("IdIngredient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BecerageIngredient_Ingredient");

                    b.Navigation("Beverage");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("kolokwium_2.Entities.Beverage", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("kolokwium_2.Entities.Ingredient", b =>
                {
                    b.Navigation("Beverages");
                });
#pragma warning restore 612, 618
        }
    }
}
